/*
 * Generates src/version.js at install/start/build time.
 * Version string: v<pkgVersion>+<commitCount>.<shortHash>[-dev]
 *   - commitCount (git rev-list --count HEAD) auto-increments with every commit
 *   - shortHash   (git rev-parse --short HEAD) identifies the exact commit
 *   - "-dev" is appended when the working tree has uncommitted changes
 * Falls back gracefully when git is unavailable (e.g. building from a tarball).
 */
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

function git(cmd, fallback) {
  try {
    return execSync(`git ${cmd}`, { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
  } catch {
    return fallback;
  }
}

const pkg = require(path.join(__dirname, '..', 'package.json'));
const count = git('rev-list --count HEAD', '0');
const hash = git('rev-parse --short HEAD', 'nogit');
const dirty = git('status --porcelain', '') ? '-dev' : '';

const version = `v${pkg.version}+${count}.${hash}${dirty}`;

const contents = `// AUTO-GENERATED by scripts/genVersion.js — do not edit, do not commit.
export const APP_VERSION = ${JSON.stringify(version)};
`;

fs.writeFileSync(path.join(__dirname, '..', 'src', 'version.js'), contents);
console.log('Generated version:', version);
